{
  "response_code": 0,
  "results": [
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for a company's profits distributed to its shareholders?",
      "choice1": "Dividends",
      "choice2": "Interest",
      "choice3": "Equity",
      "choice4": "Liabilities",
      "answer": 1
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for a legal document that outlines how a person's assets should be distributed after their death?",
      "choice1": "Living will",
      "choice2": "Trust",
      "choice3": "Will",
      "choice4": "Power of attorney",
      "answer": 3
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What does the term '401(k)' refer to?",
      "choice1": "A type of credit card",
      "choice2": "A retirement savings plan",
      "choice3": "A mortgage loan",
      "choice4": "A college savings account",
      "answer": 2
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the purpose of a stock buyback?",
      "choice1": "To increase the number of shares outstanding",
      "choice2": "To reduce the number of shares outstanding",
      "choice3": "To issue dividends",
      "choice4": "To raise capital",
      "answer": 2
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for the interest rate that banks charge each other for short-term loans?",
      "choice1": "Prime rate",
      "choice2": "Federal funds rate",
      "choice3": "Discount rate",
      "choice4": "APR",
      "answer": 2
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the purpose of a credit freeze?",
      "choice1": "To lower interest rates",
      "choice2": "To prevent identity theft",
      "choice3": "To increase credit score",
      "choice4": "To improve credit history",
      "answer": 2
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What does the term 'asset allocation' refer to in investing?",
      "choice1": "The distribution of investments among different asset classes",
      "choice2": "The total value of investments",
      "choice3": "The interest rate on investments",
      "choice4": "The time it takes for an investment to grow",
      "answer": 1
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for the cost of borrowing money, expressed as a percentage?",
      "choice1": "Principal",
      "choice2": "Dividend",
      "choice3": "Interest",
      "choice4": "APR",
      "answer": 3
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the purpose of a balance transfer on a credit card?",
      "choice1": "To increase credit limit",
      "choice2": "To transfer a balance to another card with a lower interest rate",
      "choice3": "To earn rewards points",
      "choice4": "To close the credit card account",
      "answer": 2
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for the total amount of money a person owes to creditors?",
      "choice1": "Interest",
      "choice2": "Net worth",
      "choice3": "Liabilities",
      "choice4": "Equity",
      "answer": 3
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "Which of the following represents an appreciating asset?",
      "choice1": "Gold",
      "choice2": "Car",
      "choice3": "Stocks",
      "choice4": "Furniture",
      "answer": 3
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for the increase in the value of an asset over time?",
      "choice1": "Depreciation",
      "choice2": "Amortization",
      "choice3": "Appreciation",
      "choice4": "Equity",
      "answer": 3
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "In the context of investing, what does ROI stand for?",
      "choice1": "Return on Investment",
      "choice2": "Rate of Interest",
      "choice3": "Risk of Inflation",
      "choice4": "Real Output Index",
      "answer": 1
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "Which of the following is an example of a fixed expense?",
      "choice1": "Groceries",
      "choice2": "Entertainment",
      "choice3": "Rent",
      "choice4": "Dining out",
      "answer": 3
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for a sudden, unplanned event that can have a negative impact on finances?",
      "choice1": "Windfall",
      "choice2": "Emergency",
      "choice3": "Opportunity cost",
      "choice4": "Budget",
      "answer": 2
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "Which of the following is a type of retirement account with tax advantages?",
      "choice1": "Savings account",
      "choice2": "IRA (Individual Retirement Account)",
      "choice3": "Checking account",
      "choice4": "CD (Certificate of Deposit)",
      "answer": 2
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for the process of spreading investments among different financial instruments to reduce risk?",
      "choice1": "Diversification",
      "choice2": "Concentration",
      "choice3": "Consolidation",
      "choice4": "Amortization",
      "answer": 1
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "In the context of credit scores, what does 'FICO' stand for?",
      "choice1": "Financial Investment and Credit Organization",
      "choice2": "Federal Insurance and Credit Oversight",
      "choice3": "Fair Isaac Corporation",
      "choice4": "Free Information for Credit Optimization",
      "answer": 3
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for the total value of a person's assets minus liabilities?",
      "choice1": "Net worth",
      "choice2": "Gross income",
      "choice3": "Liquid assets",
      "choice4": "Debt ratio",
      "answer": 1
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "When investing in stocks, what does the term 'bull market' refer to?",
      "choice1": "Rising stock prices and optimistic sentiment",
      "choice2": "Falling stock prices and pessimistic sentiment",
      "choice3": "Stable stock prices and cautious sentiment",
      "choice4": "Highly volatile stock prices",
      "answer": 1
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for the interest rate on a mortgage that remains fixed for the entire term of the loan?",
      "choice1": "Adjustable-rate",
      "choice2": "Variable-rate",
      "choice3": "Fixed-rate",
      "choice4": "Prime rate",
      "answer": 3
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "Which of the following is a type of investment that represents ownership in a company?",
      "choice1": "Bond",
      "choice2": "Mutual fund",
      "choice3": "Stock",
      "choice4": "Savings account",
      "answer": 3
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "In personal finance, what is the 'snowball method' often associated with?",
      "choice1": "Debt repayment",
      "choice2": "Investing",
      "choice3": "Tax planning",
      "choice4": "Savings",
      "answer": 1
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for the process of steadily investing a fixed amount in a particular investment over a long period?",
      "choice1": "Dollar-cost averaging",
      "choice2": "Market timing",
      "choice3": "Lump-sum investing",
      "choice4": "Short selling",
      "answer": 1
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "Which of the following represents a type of insurance that provides coverage for a specific period?",
      "choice1": "Whole life insurance",
      "choice2": "Term life insurance",
      "choice3": "Universal life insurance",
      "choice4": "Variable life insurance",
      "answer": 2
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for a sudden, significant drop in the value of a market or asset?",
      "choice1": "Bull market",
      "choice2": "Recession",
      "choice3": "Market correction",
      "choice4": "Crash",
      "answer": 4
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "When it comes to credit scores, what does 'credit utilization' refer to?",
      "choice1": "The length of credit history",
      "choice2": "The types of credit used",
      "choice3": "The percentage of available credit used",
      "choice4": "The number of new credit inquiries",
      "answer": 3
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "Which of the following is a type of retirement account specifically designed for self-employed individuals?",
      "choice1": "401(k)",
      "choice2": "Roth IRA",
      "choice3": "SEP IRA",
      "choice4": "IRA",
      "answer": 3
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "In the context of insurance, what does the term 'deductible' mean?",
      "choice1": "The maximum amount covered by the insurance",
      "choice2": "The minimum premium payment",
      "choice3": "The amount paid by the policyholder before the insurance coverage begins",
      "choice4": "The percentage of covered expenses paid by the policyholder",
      "answer": 3
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for a financial account that allows you to set aside money for qualified medical expenses?",
      "choice1": "401(k)",
      "choice2": "IRA",
      "choice3": "HSA (Health Savings Account)",
      "choice4": "CD (Certificate of Deposit)",
      "answer": 3
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "When it comes to taxes, what does the term 'deduction' refer to?",
      "choice1": "A decrease in taxable income",
      "choice2": "An additional tax on income",
      "choice3": "A tax credit",
      "choice4": "A tax penalty",
      "answer": 1
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "In the context of investing, what does the term 'bear market' refer to?",
      "choice1": "Rising stock prices and optimistic sentiment",
      "choice2": "Falling stock prices and pessimistic sentiment",
      "choice3": "Stable stock prices and cautious sentiment",
      "choice4": "Highly volatile stock prices",
      "answer": 2
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for the process of repaying a loan over time with regular payments?",
      "choice1": "Refinancing",
      "choice2": "Amortization",
      "choice3": "Consolidation",
      "choice4": "Foreclosure",
      "answer": 2
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "Which of the following represents a measure of a person's ability to meet short-term financial obligations?",
      "choice1": "Net worth",
      "choice2": "Cash flow",
      "choice3": "Liquidity",
      "choice4": "Credit score",
      "answer": 3
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "In the context of investing, what is the term for spreading investments across different asset classes to reduce risk?",
      "choice1": "Diversification",
      "choice2": "Concentration",
      "choice3": "Consolidation",
      "choice4": "Amortization",
      "answer": 1
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for a measure of the average change in prices of goods and services over time?",
      "choice1": "Inflation",
      "choice2": "Deflation",
      "choice3": "Recession",
      "choice4": "Stagnation",
      "answer": 1
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "Which of the following represents a type of investment with fixed periodic payments and a set maturity date?",
      "choice1": "Stock",
      "choice2": "Bond",
      "choice3": "Mutual fund",
      "choice4": "IRA",
      "answer": 2
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for a measure of a person's creditworthiness based on their credit history?",
      "choice1": "FICO score",
      "choice2": "APR",
      "choice3": "Prime rate",
      "choice4": "Loan-to-value ratio",
      "answer": 1
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "When it comes to investing, what does the term 'risk tolerance' refer to?",
      "choice1": "The likelihood of losing money",
      "choice2": "The amount of potential return",
      "choice3": "The emotional and financial ability to withstand losses",
      "choice4": "The time horizon for investments",
      "answer": 3
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for the increase in the general level of prices for goods and services?",
      "choice1": "Inflation",
      "choice2": "Deflation",
      "choice3": "Stagnation",
      "choice4": "Recession",
      "answer": 1
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "Which of the following represents a type of retirement account with tax advantages for education expenses?",
      "choice1": "Roth IRA",
      "choice2": "401(k)",
      "choice3": "529 plan",
      "choice4": "SEP IRA",
      "answer": 3
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "In the context of investing, what does the term 'liquidity' refer to?",
      "choice1": "The ease of converting an investment into cash",
      "choice2": "The potential for high returns",
      "choice3": "The diversity of investments",
      "choice4": "The time it takes for an investment to grow",
      "answer": 1
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "What is the term for the total value of a person's assets minus liabilities?",
      "choice1": "Net worth",
      "choice2": "Gross income",
      "choice3": "Liquid assets",
      "choice4": "Debt ratio",
      "answer": 1
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "When it comes to taxes, what does the term 'tax deduction' refer to?",
      "choice1": "An increase in taxable income",
      "choice2": "A decrease in taxable income",
      "choice3": "A tax credit",
      "choice4": "A tax penalty",
      "answer": 2
    },
    {
      "type": "multiple",
      "difficulty": "medium",
      "category": "Financial Literacy",
      "question": "In the context of insurance, what does the term 'premium' mean?",
      "choice1": "The amount paid by the policyholder before the insurance coverage begins",
      "choice2": "The maximum amount covered by the insurance",
      "choice3": "The percentage of covered expenses paid by the policyholder",
      "choice4": "The minimum premium payment",
      "answer": 4
    }
  ]
}
